[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFEF7"
secondaryBackgroundColor = "#FFF8DC"
textColor = "#2F4F4F"

[browser]
gatherUsageStats = false
